### ISSUE TITLE
Import error in `admin.py` 1️⃣

### ISSUE THREAD

**Issue by geekwise-ayanna** [geekwise-ayanna/django.drf.react.bank.project2.0#1]
No name 'models' in module 'main'pylint(no-name-in-module)
Cannot import 'main.models' due to syntax error 'unindent does not match any outer indentation level (<unknown>, line 11)'pylint(syntax-error)

**Comment by geekwise-ayanna** [comment]
@geekwise-estefania-flores

**Comment by geekwise-ayanna** [comment]
![image](https://user-images.githubusercontent.com/57374089/71491837-0780d100-27e8-11ea-97ad-311aae170ef0.png)

**Comment by geekwise-estefania-flores** [comment]
try changing from ```models import...``` to ```from .models import...```
